baseurl = "https://ecmascript2015.herokuapp.com/"
languageCode = "en-us"
title = "ES6 Features"
theme = "blackburn"
canonifyurls = true

[params]
  # Shown in the home page
  subtitle = "5 new EcmaScript 2015 features"
  brand = "ES6 Features"
  custom_css = ["css/custom_style.css"]

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = ""
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Arrow function"
    pre = ""
    weight = 1
    url = "/post/arrow/"
  [[menu.main]]
    name = "Modules"
    pre = ""
    weight = 2
    identifier = "Modules"
    url = "/post/Modules/"
  [[menu.main]]
    name = "Promises"
    pre = ""
    weight = 3
    identifier = "Promises"
    url = "/post/Promises/"
  [[menu.main]]
    name = "Block Scoping"
    pre = ""
    weight = 4
    url = "/post/blockScoping/"
  [[menu.main]]
    name = "Classes"
    pre = ""
    weight = 5
    url = "/post/classes/"
  [[menu.main]]
    name = "Generator"
    pre = ""
    weight = 6
    url = "/post/generator/"
    [[menu.main]]
    name = "Template Strings"
    pre = ""
    weight = 7
    url = "/post/templatestring/"
  [[menu.main]]
    name = "Destructuring"
    pre = ""
    weight = 8
    url = "/post/destructuring/"
  [[menu.main]]
    name = "Spread Operators"
    pre = ""
    weight = 9
    url = "/post/spreadoperator/"
  [[menu.main]]
    name = "Constant Keywords"
    pre = ""
    weight = 10
    url = "/post/constkeyword/"
  [[menu.main]]
    name = "Function Parameters"
    pre = ""
    weight = 11
    url = "/post/functionparameter/"
  [[menu.main]]
    name = "Objects"
    pre = ""
    weight = 12
    url = "/post/objects/"
  [[menu.main]]
    name = "Numbers"
    pre = ""
    weight = 13
    url = "/post/numbers/"